# Generated by Django 4.2.9 on 2024-12-23 00:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='info',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
